---
title: Errore del compilatore CS1626
ms.date: 07/20/2015
f1_keywords:
- CS1626
helpviewer_keywords:
- CS1626
ms.assetid: 3ba03383-eb24-4fd8-bf40-8b0f7d6baf0d
ms.openlocfilehash: 6baf2bb6f349b8603b086a54e65dc0ff65ffda03
ms.sourcegitcommit: 7588136e355e10cbc2582f389c90c127363c02a5
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 03/12/2020
ms.locfileid: "79171177"
---
# <a name="compiler-error-cs1626"></a>Errore del compilatore CS1626
Impossibile produrre un valore nel corpo di un blocco try con una clausola catch  
  
 L'istruzione yield non è consentita in un blocco try se è presente una clausola catch associata al blocco try. Per evitare questo errore, spostare l'istruzione yield dal blocco try/catch/finally oppure rimuovere il blocco catch.
  
 L'esempio seguente genera l'errore CS1626:  
  
```csharp  
// CS1626.cs  
using System.Collections;  
  
class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()  
   {  
      try  
      {  
         yield return this;  // CS1626  
      }  
      catch  
      {  
  
      }  
      finally
      {

      }
   }  
}  
  
public class CMain  
{  
   public static void Main() { }  
}  
```
